// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU3k166JAoTTlgbdjFCvjO8RuR26TFXR4',
    appId: '1:842181473067:web:01b2ea5371aed43cc38b6e',
    messagingSenderId: '842181473067',
    projectId: 'sprints-firebase',
    authDomain: 'sprints-firebase.firebaseapp.com',
    storageBucket: 'sprints-firebase.firebasestorage.app',
    measurementId: 'G-C8J0H65X9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6TCxNWfdrNuQj2hAgKIlAQ9ztZQB9gqI',
    appId: '1:842181473067:android:7ea989d6325a7cc5c38b6e',
    messagingSenderId: '842181473067',
    projectId: 'sprints-firebase',
    storageBucket: 'sprints-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfwchvsnND3QpdtW9Ire6xT2PdCILF0J8',
    appId: '1:842181473067:ios:747437ac207e81ecc38b6e',
    messagingSenderId: '842181473067',
    projectId: 'sprints-firebase',
    storageBucket: 'sprints-firebase.firebasestorage.app',
    iosBundleId: 'com.example.egyTour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfwchvsnND3QpdtW9Ire6xT2PdCILF0J8',
    appId: '1:842181473067:ios:747437ac207e81ecc38b6e',
    messagingSenderId: '842181473067',
    projectId: 'sprints-firebase',
    storageBucket: 'sprints-firebase.firebasestorage.app',
    iosBundleId: 'com.example.egyTour',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU3k166JAoTTlgbdjFCvjO8RuR26TFXR4',
    appId: '1:842181473067:web:afc3764416693668c38b6e',
    messagingSenderId: '842181473067',
    projectId: 'sprints-firebase',
    authDomain: 'sprints-firebase.firebaseapp.com',
    storageBucket: 'sprints-firebase.firebasestorage.app',
    measurementId: 'G-NXTKPGY19B',
  );

}